#include <iostream>
using namespace std;

/*
Everything is Private by delault in a class.
C++ has 3 Access Modifiers; Private, Public & Protected

1. PRIVATE: Can be accessed only inside the class
2. PUBLIC: Can be accessed outside the class
3. PROTECTED: In between Public and Private
*/

/*
CONSTRUCTOR is a special type of method which is invoked every time and object
of a class is created. 

DEFAULT CONSTRUCTOR is a constructor which is automatically generated by the compiler.
So, if we don't create a constructor, the compiler automatically gives us one.

RULES FOR CREATING A CONSTRUCTOR:
1. RETURN TYPE: Unlike other methods, it does not have a return type.

2. NAME: It has the same name as the class.

3. ACCESS: It must be public.
*/

class Employee{
public:
  string name;
  string company;
  int age;
  
  //Constructor for Class Employee
  
  
  void Introduce() {
      cout << "Name - " << name << endl;
      cout << "Company - " << company << endl;
      cout << "Age - " << age << endl;
      
  }
};

int main() {
	
	Employee emp1; //emp1 is object of type Employee
	
	//Set Attribute Values
	emp1.name = "Ishan";
	emp1.company = "YouTube";
	emp1.age = 21;
	
	//Invoke Class Method
	emp1.Introduce();
	
	Employee emp2; //emp2 is object of type Employee
	
	//Set Attribute Values
	emp2.name = "Rahul";
	emp2.company = "Amazon";
	emp2.age = 25;
	
	//Invoke Class Method
	emp2.Introduce();
	
	return 0;
}

